version: '3.7'
services:
    web:
        build: .
        env_file:
          - .env
        environment:
            - MONGO_DSN=mongodb://Buba:boba22@mongodb
            - MONGO_DB=BLOG
            - SERVER_DSN=localhost:5000
        ports:
            - 5000:5000
        depends_on:
            - mongodb

    test:
        build: .
        command: go test ./...
        env_file:
            - .env
        environment:
            - MONGO_DSN=mongodb://Buba:boba22@mongodb
            - MONGO_DB=BLOG_TEST
        depends_on:
            - mongodb

    mongodb:
        image: mongo:5.0
        environment:
            - MONGO_INITDB_ROOT_USERNAME=Buba
            - MONGO_INITDB_ROOT_PASSWORD=boba22